### PR TITLE
Fiends - BioCards and Swipers

### PR DESCRIPTION
**Pull request by moreiramj**
Everything for FiendBios and photos. Not a final commit but in a really good state for a PR can patch with updated photos and bios with new branch. Please give feedback. 🚮

### CODE REVIEW

**Comment by alejo2198** [comment]
lookin spicy. I did find a couple bugs/improvements
1. the click event on a fiend changes the card value but doest update the swiper. ex: while 'alejandro' is active, clicking on 'ben' will update the card. But 'alejandro will still have the active blue background and scale.
2. we re missing the circle fiend component for Sam
3. Ben's pic is blurry. not sure if thats my browsers fault, refreshed it 5 times, still blurry
4. icons for cards are too big. correct when comparing to figma but looking at them on browser i think they'd be better smaller. lets say 50px by 50px
5. card is too wide for tablet and desktop view. after messing with it, 400px should be max width
6. the fiends are a lil triangular. i found a mixin that lets you place them in a circle.
 https://css-tricks.com/snippets/sass/placing-items-circle/

But Matt you actually went crazy on this. that musta been a ton of work. respects

**Comment by moreiramj** [comment]
1. swiper now slides to clicked slide
2. Sam now has fiend component waiting for high res image for him. Need updated bio too.
3. Update Ben image to high res one.
4. icons have been shrunk in size.
5. card width adjusted
6. NOT READY FOR MERGE NEED WORK ON ARCH OF FIENDS

**Comment by moreiramj** [comment]
6. Implemented circle feed back (GREAT RESOURCE THANK YOU 🙏 ) 
Now smooth curve @ laptop dimensions, Sam has high res photo
NOTE: must npm i for testing and running, had to install sass to get the wheel to work properly.

**Review by alejo2198 — APPROVED** [review]
Extremely Clean code. Looks sooo good. Swiper goes crazyyy

**Pull request merged**
